Avoid some shell pitfalls

diff --git a/fuse-mount-iso b/fuse-mount-iso
--- a/fuse-mount-iso
+++ b/fuse-mount-iso
@@ -1,18 +1,14 @@
 #!/bin/sh
-MOUNTPOINT=$( zenity --file-selection \
-    --title="Select mount point" --directory --filename="$HOME/media/" )
-case $? in
-    0)
-	;;
-    *)
-	zenity --error --text="Error selecting mount point."
-	exit 1
-esac
-ERROR=$( { fuseiso $1 "$MOUNTPOINT"; } 2>&1 )
-if [ $? -eq 0 ]; then
+MOUNTPOINT="$( zenity --file-selection \
+    --title="Select mount point" --directory --filename="$HOME/media/" )"
+if [ "$?" -ne 0 ]; then
+    zenity --error --text="Error selecting mount point."
+    exit 1
+fi
+if ERROR="$( { fuseiso "$1" "$MOUNTPOINT"; } 2>&1 )"; then
     exit 0
 else
-    test "$ERROR" && MSG="$ERROR" || \
+    [ "$ERROR" ] && MSG="$ERROR" || \
 	MSG="Unknown error while mounting $1 to $MOUNTPOINT"
     zenity --warning --text="$MSG"
     exit 1
